//API key
export const API_KEY = 'JXiBlfAzq1GkA9vx3evBwHJQKaIlCMm7';

//Current Weather
export const SET_CURRENT_WEATHER = 'SET_CURRENT_WEATHER';
export const START_SET_CURRENT_WEATHER = 'START_SET_CURRENT_WEATHER';
export const FAIL_SET_CURRENT_WEATHER = 'FAIL_SET_CURRENT_WEATHER';
export const CLEAR_CURRENT_WEATHER = 'CLEAR_CURRENT_WEATHER';

//5 Days Weather
export const SET_5_DAYS_WEATHER = 'SET_5_DAYS_WEATHER';
export const START_SET_5_DAYS_WEATHER = 'START_SET_5_DAYS_WEATHER';
export const FAIL_SET_5_DAYS_WEATHER = 'FAIL_SET_5_DAYS_WEATHER'
export const CLEAR_DAILY_FORECAST = 'CLEAR_DAILY_FORECAST';

//Locations
export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION';
export const SET_LOCATIONS_FOR_AC = 'SET_LOCATIONS_FOR_AC';
export const ADD_LOCATION_TO_STATE = 'ADD_LOCATION_TO_STATE';
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';
export const LOCATION_REQUEST_START = 'LOCATION_REQUEST_START';
export const LOCATION_REQUEST_FAIL = 'LOCATION_REQUEST_FAIL';
export const CLEAR_LOCATIONS = 'CLEAR_LOCATIONS';

//Modal
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';